### ISSUE TITLE
maven sample with Java sample codes 

### ISSUE THREAD

**Issue by danyaljj** [scala/scala-module-dependency-sample#4]
I wish the maven sample had examples also containing java files, in addition to scala files.
I tried adding something very quickly, but will give it another try.

**Comment by danyaljj** [comment]
I myself create one btw: https://github.com/danyaljj/sampleMixedScalaJavaMavenProject

**Comment by SethTisue** [comment]
I think it's better to keep this repo focused on demonstrating Scala module use _only_, and not include other things in the template.
