### ISSUE TITLE
Import to Eclipse and prompt errors

### ISSUE THREAD

**Issue by chendeshen** [scala/scala-module-dependency-sample#5]
Description Resource    Path    Location    Type
Plugin execution not covered by lifecycle configuration: net.alchim31.maven:scala-maven-plugin:3.1.6:compile (execution: default, phase: compile)   pom.xml /scala-module-dependency-sample line 79 Maven Project Build Lifecycle Mapping Problem

**Comment by SethTisue** [comment]
need more context here? what's this about, what are the steps to reproduce?
